#
# i-Parapheur Web
# Copyright (C) 2019-2022 Libriciel-SCOP
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

stages:
  - package
  - publish
  - deploy
  - e2e-tests

variables:
  NIGHTLY:
    value: "FALSE"
    description: "If set to TRUE, will start the nightly jobs"
  FORCE_RESET_DATA:
    value: "FALSE"
    description: "If set to TRUE, deploy jobs will wipe data even if it normally don't (acceptance, dev)"
  PACKAGE_NAME: iparapheur-${CI_COMMIT_REF_NAME}
  PACKAGE_NAME_WITH_EXTENSION: ${PACKAGE_NAME}.tar.gz
  IPARAPHEUR_DOCKER_ELEMENTS_PATH: "/opt/iParapheur"
  INIT_SCRIPT: "ip5-compose-dev.sh"
  DOCKER_COMPOSE_OVERRIDES_DEV: "docker-compose.override.dev.yml docker-compose.override.tests-linux.yml"
  DOCKER_COMPOSE_OVERRIDES_TAG: "docker-compose.override.tests-linux.yml"

.e2e-test-config:
  variables: &e2e-test-config
    TARGETED_ENVIRONNEMENT_URL: ${E2E_TESTS_TARGET_SERVER_URL}
    TARGETED_ENVIRONNEMENT_USER: ${E2E_TESTS_TARGET_SERVER_USER}
    SSH_PRIVATE_KEY_B64: ${E2E_TESTS_SSH_PRIVATE_KEY_B64}
    RESET_DATA: "TRUE"
    OVERRIDE_DOCKER_COMPOSE_FILES: ${DOCKER_COMPOSE_OVERRIDES_TAG}
  environment: &e2e-test-environment
    name: Charge/Tests e2e
    url: https://${E2E_TESTS_TARGET_SERVER_URL}

.acceptance-config:
  variables: &acceptance-config
    TARGETED_ENVIRONNEMENT_URL: ${ACCEPTANCE_TARGET_SERVER_URL}
    TARGETED_ENVIRONNEMENT_USER: ${ACCEPTANCE_TARGET_SERVER_USER}
    SSH_PRIVATE_KEY_B64: ${ACCEPTANCE_SSH_PRIVATE_KEY_B64}
    RESET_DATA: "FALSE"
    OVERRIDE_DOCKER_COMPOSE_FILES: ${DOCKER_COMPOSE_OVERRIDES_TAG}
  environment: &acceptance-environment
    name: Recette
    url: https://${ACCEPTANCE_TARGET_SERVER_URL}

.dev-config:
  variables: &dev-config
    TARGETED_ENVIRONNEMENT_URL: ${DEV_TARGET_SERVER_URL}
    TARGETED_ENVIRONNEMENT_USER: ${DEV_TARGET_SERVER_USER}
    SSH_PRIVATE_KEY_B64: ${DEV_SSH_PRIVATE_KEY_B64}
    RESET_DATA: "FALSE"
    OVERRIDE_DOCKER_COMPOSE_FILES: ${DOCKER_COMPOSE_OVERRIDES_DEV}
  environment: &dev-environment
    name: Dev
    url: https://${DEV_TARGET_SERVER_URL}

# <editor-fold desc="Package">

.prepare-package: &prepare-package
  script:
    - echo -e "📦📦📦 \e[42mPackaging ${PACKAGE_NAME}\e[0m 📦📦📦"
    - packageFiles=(
      "docker-compose.yml"
      "docker-compose.ipng.yml"
      "docker-compose.override.init.yml"
      ".env.dist"
      "LICENSE.md"
      "README.md"
      "src/main/resources/nginx/iparapheur.conf.template"
      "src/main/resources/nginx/iparapheur.init.conf.template"
      "src/main/resources/content"
      "src/main/resources/postgres/docker-entrypoint-initdb.d"
      "src/main/resources/keycloak"
      "src/main/resources/prometheus/alert.rules"
      "src/main/resources/prometheus/prometheus.yml"
      "src/main/resources/rgpd/rgpd-template.json"
      "src/main/resources/vault"
      )
    - tar cfz ${PACKAGE_NAME_WITH_EXTENSION} --files-from <(printf "%s\n" "${packageFiles[@]}")

package_prod:
  stage: package
  only: [ tags ]
  <<: *prepare-package
  artifacts:
    name: ${PACKAGE_NAME}
    paths:
      - ${PACKAGE_NAME_WITH_EXTENSION}

package:
  stage: package
  except: [ tags ]
  <<: *prepare-package
  artifacts:
    name: ${PACKAGE_NAME}
    paths:
      - ${PACKAGE_NAME_WITH_EXTENSION}
    expire_in: 30 days

# </editor-fold desc="Package">

# <editor-fold desc="Publish">

publish:
  stage: publish
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_TAG != null
      when: always
      variables:
        NEXUS_FINAL_PATH: ${NEXUS_PUBLIC_PATH}
    - when: manual
      variables:
        NEXUS_FINAL_PATH: ${NEXUS_PRIVATE_PATH}
  script:
    - echo "Publishing ${PACKAGE_NAME_WITH_EXTENSION} to https://${NEXUS_HOST}/repository/${NEXUS_FINAL_PATH}/${PACKAGE_NAME_WITH_EXTENSION}"
    - curl -v -u ${REGISTRY_CONTAINER_USER}:${REGISTRY_CONTAINER_PASSWORD} --upload-file ${PACKAGE_NAME_WITH_EXTENSION} https://${NEXUS_HOST}/repository/${NEXUS_FINAL_PATH}/${PACKAGE_NAME_WITH_EXTENSION}

# </editor-fold desc="Publish">

# <editor-fold desc="Deploy">

.preparing-ssh: &preparing-ssh
  - echo -e "🕵🏽 \e[46mPreparing ssh agent\e[0m 🕵🏽"
  - eval $(ssh-agent -s)
  - ssh-add <(echo "${SSH_PRIVATE_KEY_B64}" | base64 --decode)
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

.copying-deployment-files: &copying-deployment-files
  - echo -e "📤 \e[46mCopying and extracting ${PACKAGE_NAME_WITH_EXTENSION}, ${INIT_SCRIPT} and ${OVERRIDE_DOCKER_COMPOSE_FILES} to ${TARGETED_ENVIRONNEMENT_USER}@${TARGETED_ENVIRONNEMENT_URL}:${IPARAPHEUR_DOCKER_ELEMENTS_PATH}/\e[0m 📤"
  - scp ./${PACKAGE_NAME_WITH_EXTENSION} ${TARGETED_ENVIRONNEMENT_USER}@${TARGETED_ENVIRONNEMENT_URL}:${IPARAPHEUR_DOCKER_ELEMENTS_PATH}/${PACKAGE_NAME_WITH_EXTENSION}
  - ${APPLY_COMMAND} "sudo tar -xf ${IPARAPHEUR_DOCKER_ELEMENTS_PATH}/${PACKAGE_NAME_WITH_EXTENSION} --directory ${IPARAPHEUR_DOCKER_ELEMENTS_PATH}"
  - scp ./${INIT_SCRIPT} ${TARGETED_ENVIRONNEMENT_USER}@${TARGETED_ENVIRONNEMENT_URL}:${IPARAPHEUR_DOCKER_ELEMENTS_PATH}/${INIT_SCRIPT}
  - ${APPLY_COMMAND} "sudo chmod 770 ${IPARAPHEUR_DOCKER_ELEMENTS_PATH}/${INIT_SCRIPT}"
  - ${APPLY_COMMAND} "sudo chgrp deployment ${IPARAPHEUR_DOCKER_ELEMENTS_PATH}/${INIT_SCRIPT}"
  - |
    for OVERRIDE_DOCKER_COMPOSE_FILE in ${OVERRIDE_DOCKER_COMPOSE_FILES}; do
      scp ./${OVERRIDE_DOCKER_COMPOSE_FILE} ${TARGETED_ENVIRONNEMENT_USER}@${TARGETED_ENVIRONNEMENT_URL}:${IPARAPHEUR_DOCKER_ELEMENTS_PATH}/${OVERRIDE_DOCKER_COMPOSE_FILE}
    done

.deploying-app: &deploying-app
  - echo -e "🚀 \e[46mDeploying application using ${OVERRIDE_DOCKER_COMPOSE_FILES}\e[0m 🚀"
  - if [[ ${FORCE_RESET_DATA} == "TRUE" && ${RESET_DATA} == "FALSE" ]]; then echo -e "🧹⚠️ \e[41mData will be reset\e[0m ⚠️🧹"; fi
  - ${APPLY_COMMAND} "cd ${IPARAPHEUR_DOCKER_ELEMENTS_PATH} && docker-compose down --volumes --remove-orphan"
  - ${APPLY_COMMAND} "docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}"
  - DOCKER_COMPOSE_FILES=("-f docker-compose.yml")
  - for OVERRIDE_DOCKER_COMPOSE_FILE in ${OVERRIDE_DOCKER_COMPOSE_FILES}; do DOCKER_COMPOSE_FILES+=(" -f ${OVERRIDE_DOCKER_COMPOSE_FILE}"); done
  - ${APPLY_COMMAND} "cd ${IPARAPHEUR_DOCKER_ELEMENTS_PATH} && docker-compose ${DOCKER_COMPOSE_FILES[@]} pull"
  - if [[ ${FORCE_RESET_DATA} == "TRUE" || ${RESET_DATA} == "TRUE" ]]; then ${APPLY_COMMAND} "cd ${IPARAPHEUR_DOCKER_ELEMENTS_PATH} && sudo ${IPARAPHEUR_DOCKER_ELEMENTS_PATH}/${INIT_SCRIPT} setup --force --ignore-override-compose --dont-start-app"; fi
  - ${APPLY_COMMAND} "cd ${IPARAPHEUR_DOCKER_ELEMENTS_PATH} && docker-compose ${DOCKER_COMPOSE_FILES[@]} up -d"
  - echo -e "⏳️ \e[46mWaiting for the application to be up\e[0m ⌛️️"
  - x=1; while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' https://${TARGETED_ENVIRONNEMENT_URL}/api/actuator/info)" != "200" && $x -le 60 ]]; do sleep 5; echo ⌛️️ $(( x++ )) ⏳; done || false
  - if [[ "$(curl -s -o /dev/null -w ''%{http_code}'' https://${TARGETED_ENVIRONNEMENT_URL}/api/actuator/info)" != "200" ]]; then echo -e "❤️‍🩹❤️‍🩹❤️‍🩹 \e[41mApplication not started\e[0m ❤️‍🩹❤️‍🩹❤️‍🩹"; exit 1; fi

.deploy-job:
  variables:
    APPLY_COMMAND: "ssh -tt ${TARGETED_ENVIRONNEMENT_USER}@${TARGETED_ENVIRONNEMENT_URL}"
  needs:
    - job: package
      optional: true
    - job: package_prod
      optional: true
  before_script:
    - echo -e "🚀🚀🚀 \e[42mDeploying ${CI_COMMIT_REF_NAME} on ${TARGETED_ENVIRONNEMENT_URL} with user ${TARGETED_ENVIRONNEMENT_USER}\e[0m 🚀🚀🚀"
    - *preparing-ssh
  script:
    - *copying-deployment-files
    - *deploying-app
    - echo -e "🎉🎉🎉 \e[42m${CI_COMMIT_REF_NAME} successfully deployed on ${TARGETED_ENVIRONNEMENT_URL}\e[0m 🎉🎉🎉"

strict-e2e-tests-deploy:
  extends: [ .deploy-job ]
  stage: e2e-tests
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $NIGHTLY == "TRUE"
      when: always
      variables:
        OVERRIDE_DOCKER_COMPOSE_FILES: ${DOCKER_COMPOSE_OVERRIDES_DEV}
    - if: $CI_COMMIT_BRANCH == 'develop' || $CI_COMMIT_TAG != null
      when: always
    - when: manual
  allow_failure: false
  variables: *e2e-test-config
  environment: *e2e-test-environment

tolerant-e2e-tests-deploy:
  extends: [ .deploy-job ]
  stage: e2e-tests
  needs:
    #    must repeat package here because extends overwrites instead of merge properties
    - job: package
      optional: true
    - job: package_prod
      optional: true
    - strict-e2e-tests-test
  only: [ develop ]
  allow_failure: false
  variables: *e2e-test-config
  environment: *e2e-test-environment

acceptance-deploy:
  extends: [ .deploy-job ]
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_TAG != null
      when: always
    - when: manual
  variables: *acceptance-config
  environment: *acceptance-environment

dev-deploy:
  extends: [ .deploy-job ]
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $NIGHTLY == "TRUE"
      when: always
    - when: manual
  variables: *dev-config
  environment: *dev-environment

# </editor-fold desc="Deploy">

# <editor-fold desc="E2e tests">

.e2e-tests:
  image: markhobson/maven-chrome:jdk-11
  stage: e2e-tests
  script:
    - apt-get update && apt-get install --assume-yes --no-install-recommends --show-upgraded libxml2-utils=2.9.10+dfsg-6.7+deb11u2 python3-pip=20.3.4-4+deb11u1 poppler-utils=20.09.0-3.1 xmlsec1=1.2.31-1 zip=3.0-12 && pip3 install jsonpath-ng==1.5.3 Pillow==9.2.0 PyPDF2==2.10.0
    - echo "Test ${CI_COMMIT_REF_NAME} deployed on ${E2E_TESTS_TARGET_SERVER_URL} with Karate - These tests mustn't fail"
    - ./gradlew test -Dkarate.options="${KARATE_ADDITIONAL_TAGS}" -Dkarate.headless=true -Dkarate.baseUrl="https://${E2E_TESTS_TARGET_SERVER_URL}" -Dkarate.chromeBin=/opt/google/chrome/google-chrome
  after_script:
    - folders="${REPORT_NAME}-`date +%Y%m%d-%H%M%S`.zip" && zip -r "${folders}" "build/ip5-folders" && url=`curl -s -T "./${folders}" "https://curl.libriciel.fr/${folders}"` && echo "${url}" > "build/url.txt" && echo "Test result folders available ${url}"
  artifacts:
    when: always
    name: ${REPORT_NAME}
    paths:
      - build/karate-reports
      - build/url.txt

strict-e2e-tests-test:
  extends: [ .e2e-tests ]
  variables:
    REPORT_NAME: "Karate - tests strict"
    KARATE_ADDITIONAL_TAGS: "--tags @demo-simple-bde,@legacy-bridge,@formats-de-signature,@metadonnees --tags ~@fixme-ip --tags ~@ip4 "
  needs:
    - job: strict-e2e-tests-deploy
      optional: true
  allow_failure: false

tolerant-e2e-tests-test:
  extends: [ .e2e-tests ]
  variables:
    REPORT_NAME: "Karate - tests tolerant"
    KARATE_ADDITIONAL_TAGS: "--tags @demo-simple-bde,@legacy-bridge,@formats-de-signature,@metadonnees --tags ~@ip4 "
  needs: [ tolerant-e2e-tests-deploy ]
  only: [ develop ]
  allow_failure: true

# </editor-fold desc="E2e tests">
