#
# i-Parapheur Web
# Copyright (C) 2019-2021 Libriciel-SCOP
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

image: docker/compose:debian-1.29.1


stages:
  - test
  - package


# <editor-fold desc="Test">


pull:
  stage: test
  script:
    - cp .env.dist .env
    - docker-compose pull --quiet


# </editor-fold desc="Test">


# <editor-fold desc="Package">


zip:
  stage: package
  script:
    - echo "Packaging things..."
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - docker-compose.yml
      - docker-compose.ipng.yml
      - .env.dist
      - LICENSE.md
      - README.md
      # TODO : Add some proper doc (PDF?)


# </editor-fold desc="Package">
