kind: Service
apiVersion: v1
metadata:
  name: alfresco
  namespace: iparapheur
  labels:
    app: alfresco
spec:
  type: ClusterIP
  selector:
    app: alfresco
  ports:
    - protocol: TCP
      port: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alfresco
  name: alfresco
  namespace: iparapheur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alfresco
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: alfresco
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: " -XX:+UseContainerSupport -Ddeployment.method=DOCKER_COMPOSE\n-Ddb.driver=org.postgresql.Driver
            -Ddb.username=alfresco -Ddb.password=alfresco -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
            -Dalfresco.host=alfresco -Dalfresco.port=8080 -Dalf.root=/var/lib/alfresco\n-Dsolr.host=solr6
            -Dsolr.port=8983 -Dsolr.secureComms=none -Dsolr.base.url=/solr -Dindex.subsystem.name=solr6\n-Dheartbeat.enabled=false
            -Dtransform.service.enabled=false -Dlocal.transform.service.enabled=false
            -Dlegacy.transform.service.enabled=false -Dmessaging.subsystem.autoStart=false
            -Dsystem.workflow.engine.activiti.enabled=false "
        image: alfresco/alfresco-content-repository-community:6.2.0-ga
        name: alfresco
        resources:
          limits:
            memory: "1610612736"
        tty: true
        volumeMounts:
        - mountPath: /usr/local/tomcat/alf_data
          name: alfresco-data
        - mountPath: /usr/local/tomcat/shared/classes/alfresco/extension/ip-custom-models.xml
          name: alfresco-ip-custom-models
        - mountPath: /usr/local/tomcat/shared/classes/alfresco/extension/custom-model-context.xml
          name: alfresco-custom-model-context
      restartPolicy: Always
      volumes:
      - name: alfresco-data
        hostPath:
          path: /home/marc/dev/i-Parapheur-v5/compose/data/alfresco
          type: DirectoryOrCreate

      - name: alfresco-ip-custom-models
        hostPath:
          path: /home/marc/dev/i-Parapheur-v5/compose/src/main/resources/content/ip-custom-models.xml
          type: FileOrCreate
      - name: alfresco-custom-model-context
        hostPath:
          path: /home/marc/dev/i-Parapheur-v5/compose/src/main/resources/content/custom-model-context.xml
          type: FileOrCreate
status: {}
