#
# i-Parapheur
# Copyright (C) 2019-2021 Libriciel-SCOP
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

version: '2.4'

services:


  nginx:
    image: nginx:alpine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    mem_limit: 64M
    memswap_limit: 64m
    volumes:
      - ./src/main/resources/nginx/iparapheur.develop.conf.template:/etc/nginx/templates/iparapheur.conf.template


  core:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/ip-core:develop
    extra_hosts:
      - "${APPLICATION_HOST}:host-gateway"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=dev
    mem_limit: 1G
    memswap_limit: 1G
    ports:
      - "8080:8080"


  web:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/ip-web:develop
    mem_limit: 64m
    memswap_limit: 64m
    environment:
      - VERSION=5.0.0-beta01-DEV
    ports:
      - "4200:80"


  workflow:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/workflow:develop
    mem_limit: 1G
    memswap_limit: 1G
    ports:
      - "10080:8080"


  pastell-connector:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/pastell-connector:develop
    ports:
      - "8002:8080"


  external-signature-connector:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/external-signature-connector:develop
    ports:
      - "2757:8080"

  legacy-bridge:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/legacy-bridge:develop
    ports:
      - "2758:8080"


  crypto:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/ip-crypto:develop
    mem_limit: 256M
    memswap_limit: 256m
    ports:
      - "8085:8080"


  libersign:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/signature/libersign:latest
    ports:
      - "8079:80"


  pes-viewer:
    mem_limit: 256M
    memswap_limit: 256m
    ports:
      - "8888:8888"

  pdf-stamp:
    mem_limit: 256M
    memswap_limit: 256m
    ports:
      - "8889:8080"


  # Non-libriciel services

  alfresco:
    mem_limit: 1024M
    memswap_limit: 1024m
    ports:
      - "9009:8080"


  #solr6:
  #  mem_limit: 1536M
  #  memswap_limit: 1536m
  #  ports:
  #    - 8983:8983


  postgres:
    mem_limit: 512M
    memswap_limit: 512m
    ports:
      - "5432:5432"


  keycloak:
    mem_limit: 768M
    memswap_limit: 768M
    ports:
      - "9090:8080"


  matomo:
    mem_limit: 512M
    memswap_limit: 512m


  redis:
    image: redis:6.0-alpine
    mem_limit: 64M
    memswap_limit: 64m
    ports:
      - "6379:6379"


  smtp:
    image: tophfr/mailcatcher:0.7.1
    ports:
      - "1025:25"
      - "1080:80"


  vault:
    ports:
      - "8200:8200"


  prometheus:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9091:9090"
    volumes:
      - ./src/main/resources/prometheus/alert.rules:/etc/prometheus/alert.rules
      - ./src/main/resources/prometheus/prometheus-dev.yml:/etc/prometheus/prometheus.yml


  filetransfer:
    ports:
      - "1807:8080"
