# i-Parapheur
# Copyright (C) 2019 Libriciel-SCOP
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# ========================================================================

# This docker-compose file will spin up an ACS cluster on a local host or on a server and it requires a minimum of 16GB Memory to distribute among containers.
# Limit container memory and assign X percentage to JVM.  There are couple of ways to allocate JVM Memory for ACS Containers
# For example: 'JAVA_OPTS: "$JAVA_OPTS -XX:+PrintFlagsFinal -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"'
# But, as per Oracle docs (https://docs.oracle.com/javase/9/gctuning/parallel-collector1.htm#JSGCT-GUID-CAB83393-3438-44ED-98F0-D15641B43C7D)
# If container memory is not explicitly set, then the above flags will default max heap to 1/4th of container's memory which may not be ideal.
# Hence, setting up explicit Container memory and then assigning a percentage of it to the JVM for performance tuning.

# Note: The docker-compose file from github.com is a limited trial that goes into read-only mode after 2 days.
# Get the latest docker-compose.yml file with a 30-day trial license by accessing the Alfresco Content Services trial download page at:
# https://www.alfresco.com/platform/content-services-ecm/trial/download

version: '3.7'

services:

  nginx:
    image: nginx:alpine
    tty: true
    volumes:
      - ./src/main/resources/nginx/:/etc/nginx/conf.d/
      - ./src/main/resources/nginx/ssl/:/etc/nginx/ssl/
    ports:
      - 80:80
      - 443:443


  redis:
    image: redis:5.0.3
    tty: true
    # ports:
    #   - 6379:6379


  core:
    image: gitlab.libriciel.fr:4567/i-parapheur/components/ip-core:develop
    # build: ../ip-core
    tty: true
    depends_on:
      - postgres
      - alfresco
      - flowable-rest
    volumes:
      - ./resources/core/application.yml:/application.yml
      - ./resources/core/sentry.properties:/sentry.properties
    external_links:
      - nginx:iparapheur.dom.local


  web:
    image: ip-web:develop
    # build: ../ip-web
    tty: true


  crypto:
    image: gitlab.libriciel.fr:4567/i-parapheur/components/ip-crypto:latest
    # build: ../ip-crypto
    tty: true
    volumes:
      - ./src/main/resources/crypto/application.yml:/application.yml
      - ./src/main/resources/crypto/sentry.properties:/sentry.properties
    # ports:
    #   - 8085:8080


  alfresco:
    image: alfresco/alfresco-content-repository-community:6.1.1
    tty: true
    environment:
      JAVA_OPTS: "
                  -Ddb.driver=org.postgresql.Driver
                  -Ddb.username=alfresco
                  -Ddb.password=alfresco
                  -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                  -Dalfresco.host=alfresco
                  -Dalfresco.port=8080
                  -Dalf.root=/var/lib/alfresco
                  -Dheartbeat.enabled=false
                  -Xmx1g
                  "
    volumes:
      - ./data/alfresco:/usr/local/tomcat/alf_data
    # ports:
    #   - 9000:8080


  postgres:
    build: src/main/resources/postgres
    tty: true
    environment:
      - POSTGRES_PASSWORD=libriciel2k18
      - POSTGRES_USER=root
      - DB_TO_CREATE=alfresco,flowable,keycloak,ipcore
    command: postgres -c max_connections=500 -c log_min_messages=LOG
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432


  flowable-rest:
    image: flowable/flowable-rest:6.4.2
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
    tty: true
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/flowable
      - SPRING_DATASOURCE_USERNAME=flowable
      - SPRING_DATASOURCE_PASSWORD=flowable
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - FLOWABLE_REST_APP_ADMIN_USER-ID=kermit
      - FLOWABLE_REST_APP_ADMIN_PASSWORD=kermit
    # ports:
    #   - 9999:8080


  keycloak:
    image: jboss/keycloak:6.0.1
    tty: true
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - KEYCLOAK_IMPORT=/tmp/keycloak.json
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
      - ./resources/keycloak/keycloak.json:/tmp/keycloak.json
    # ports:
    #   - 9090:8080


  matomo:
    image: matomo:3.11-apache
    tty: true
    depends_on:
      - matomo-db
    volumes:
      - ./src/main/resources/matomo/config/:/var/www/html/config/
      - ./src/main/resources/matomo/plugins/CustomDimensions:/var/www/html/plugins/CustomDimensions
    ports:
      - 9080:80
      - 9083:443
  matomo-db:
    image: mariadb:10.3
    tty: true
    volumes:
      - ./data/matomo-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=libriciel2k18
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
      - MYSQL_PASSWORD=matomo
