#
# i-Parapheur
# Copyright (C) 2019-2022 Libriciel-SCOP
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#



services:


  ipng:
    image: registry.libriciel.fr:443/public/signature/ipng:1.0.0-beta03
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8081:8081
    environment:
      - KEYCLOAK_AUTH_PROTOCOL
      - APPLICATION_PROTOCOL
      - APPLICATION_HOST
      - KEYCLOAK_HOST
      - KEYCLOAK_PORT
      - KEYCLOAK_CLIENT_ID
      - KEYCLOAK_CLIENT_SECRET
      - IPNG_HOST
      - IPNG_MSPID
      - MONGO_DB_USR
      - MONGO_DB_PWD
    volumes:
      - ./data/ipng/wallet:/wallet
      - ./data/ipng/ca-certs:/crypto-config
      - ./src/main/resources/ipng/application.properties:/application.properties
      - ./data/ipng/connection-profile.yml:/connection-profile.yml
    restart: unless-stopped

  mongo:
    image: mongo:4.2.18-bionic
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USR}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PWD}
    volumes:
      - ./data/ipng/cache-db:/data/db:rw
    ports:
      - 27017:27017

  nginx:
    volumes:
      - ./src/main/resources/nginx/iparapheur.ipng.conf.template:/etc/nginx/templates/iparapheur.conf.template

  core:
    volumes:
      - ./src/main/resources/core/application-ipng.yml:/application.yml
