# i-Parapheur
# Copyright (C) 2019-2020 Libriciel-SCOP
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

version: '2.4'

services:


  nginx:
    image: nginx:mainline-alpine
    volumes:
      - ./src/main/resources/nginx/iparapheur.develop.conf:/etc/nginx/conf.d/iparapheur.conf
      - ./src/main/resources/nginx/ssl/:/etc/nginx/ssl/


  redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379


  core:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/ip-core:develop
    ports:
      - 8080:8080


  web:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/ip-web:develop
    ports:
      - 4200:80


  pes-viewer:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/pes-viewer:dev
    ports:
      - 8889:8888


  workflow:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/workflow:develop
    ports:
      - 10080:8080


  crypto:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/ip-crypto:develop
    ports:
      - 8085:8080


  libersign:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/signature/libersign:latest


  pdf-stamp:
    ports:
      - 8888:8080


  alfresco:
    ports:
      - 9009:8080


  solr6:
    ports:
      - 8983:8983


  postgres:
    ports:
      - 5432:5432


  keycloak:
    ports:
      - 9090:8080


  vault:
    ports:
      - 8200:8200

