#
# i-Parapheur
# Copyright (C) 2019-2022 Libriciel-SCOP
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

services:


  nginx:
    image: nginx:latest
    volumes:
      - ./src/main/resources/nginx/iparapheur.develop.conf.template:/etc/nginx/templates/iparapheur.conf.template


  core:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/i-parapheur/ip-core:develop
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=dev
    ports:
      - "8080:8080"


  web:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/i-parapheur/ip-web:develop
    environment:
      - VERSION=5.0.0-develop
    ports:
      - "4200:80"


  redis:
    image: redis:6.0-alpine
    ports:
      - "6379:6379"


  pes-viewer:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/i-parapheur/pes-viewer:develop
    ports:
      - "8888:8080"


  workflow:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/i-parapheur/workflow:develop
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=dev
    ports:
      - "10080:10080"


  pastell-connector:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/i-parapheur/pastell-connector:develop
    ports:
      - "8002:8080"


  external-signature-connector:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/i-parapheur/external-signature-connector:develop
    ports:
      - "2757:8080"


  legacy-bridge:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/i-parapheur/legacy-bridge:develop
    ports:
      - "2758:8080"


  crypto:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/i-parapheur/ip-crypto:develop
    ports:
      - "8085:8080"


  libersign:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/signature/libersign:latest


  pdf-stamp:
    image: gitlab.libriciel.fr:4567/outils/pdf-stamp:develop
    ports:
      - "8889:8080"


  alfresco:
    ports:
      - "9009:8080"


  transform-core-aio:
    ports:
      - "8090:8090"


  postgres:
    ports:
      - "5432:5432"


  keycloak:
    ports:
      - "9090:8080"
    # environment:
    #   - KEYCLOAK_LOGLEVEL=DEBUG


  feeder:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-feeder:develop


  smtp:
    image: tophfr/mailcatcher:0.7.1
    ports:
      - "1025:25"
      - "1080:80"


  vault:
    # For some reasons, macOS' Docker uses kebab-case in container names.
    # We want to ease the copy/paste from the README file.
    container_name: 'compose_vault_1'
    ports:
      - "8200:8200"


  prometheus:
    ports:
      - "9091:9090"
    volumes:
      - ./src/main/resources/prometheus/alert.rules:/etc/prometheus/alert.rules
      - ./src/main/resources/prometheus/prometheus-dev.yml:/etc/prometheus/prometheus.yml


  filetransfer:
    ports:
      - "1807:8080"
