#
# iparapheur
# Copyright (C) 2019-2023 Libriciel-SCOP
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#


services:


  nginx:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/i-parapheur/nginx/develop:latest-dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    memswap_limit: 256M


  core:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/i-parapheur/ip-core/develop:latest
    extra_hosts:
      - "${APPLICATION_HOST}:host-gateway"
    volumes:
      - ./src/main/resources/core/application-dev.yml:/application.yml
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=dev-container
    memswap_limit: 2G
    ports:
      - "8080:8080"


  web:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/i-parapheur/ip-web/develop:latest
    memswap_limit: 64M
    environment:
      - VERSION=5.1.1-develop
    ports:
      - "4200:80"


  workflow:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/i-parapheur/workflow/develop:latest
    memswap_limit: 768M
    volumes:
      - ./src/main/resources/workflow/application-dev-docker.yml:/application.yml
    ports:
      - "10080:8080"


  pastell-connector:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/i-parapheur/pastell-connector/develop:latest
    ports:
      - "8002:8080"


  external-signature-connector:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/i-parapheur/external-signature-connector:develop
    ports:
      - "2757:8080"


  legacy-bridge:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/i-parapheur/legacy-bridge:develop
    ports:
      - "2758:8080"


  crypto:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/i-parapheur/ip-crypto:develop
    memswap_limit: 3G
    ports:
      - "8085:8080"


  libersign:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/signature/libersign-natif:develop
    ports:
      - "8079:80"


  pes-viewer:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/i-parapheur/pes-viewer:develop
    memswap_limit: 1536M
    ports:
      - "8888:8888"


  pdf-stamp:
    image: gitlab.libriciel.fr:4567/outils/pdf-stamp:develop
    memswap_limit: 1G
    ports:
      - "8889:8080"


  # Non-libriciel services


  alfresco:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/i-parapheur/alfresco/develop:latest
    memswap_limit: 1536M
    ports:
      - "9009:8080"


  transform-core-aio:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/i-parapheur/alfresco-transform-core-aio:develop
    # ports:
    #   - "8090:8090"


  libriciel-engine-extractors:
    # image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/i-parapheur/ip-alfresco-transform-extractors:develop
    ports:
      - "8090:8090"


  postgres:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/i-parapheur/ip-postgresql/develop:latest
    memswap_limit: 1G
    ports:
      - "5432:5432"


  keycloak:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/i-parapheur/keycloak/develop:latest
    command: start  --import-realm
    memswap_limit: 1536M
    ports:
      - "9090:8080"
    environment:
      - KC_HOSTNAME_STRICT_BACKCHANNEL=true
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
    # - KC_LOG_LEVEL=TRACE


  redis:
    memswap_limit: 128M
    ports:
      - "6379:6379"


  smtp:
    image: tophfr/mailcatcher:0.7.1
    ports:
      - "1025:25"
      - "1080:80"


  vault:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/i-parapheur/ip-vault/develop:latest
    ports:
      - "8200:8200"


  prometheus:
    image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/i-parapheur/ip-prometheus/develop:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9091:9090"
    volumes:
      - ./src/main/resources/prometheus/prometheus-dev.yml:/etc/prometheus/prometheus.yml


#  filetransfer:
#    ports:
#      - "1807:8080"
