


server {
    listen 443 ssl http2;
    server_name ca.blucas-ovh.iparapheur.dev.libriciel.net;

    ssl_certificate /etc/nginx/ssl/ca/ca.blucas-ovh.iparapheur.dev.libriciel.net-cert.pem;
    ssl_certificate_key /etc/nginx/ssl/ca/ca.blucas-ovh.iparapheur.dev.libriciel.net.key;

    location / {
        grpc_pass grpcs://host.docker.internal:7054;
    }
}
