server {
    listen 443 ssl http2;
    server_name peer1.blucas-ovh.iparapheur.dev.libriciel.net;

    ssl_certificate /etc/nginx/ssl/peer1/server.crt;
    ssl_certificate_key /etc/nginx/ssl/peer1/server.key;

    location / {
        grpc_pass grpc://host.docker.internal:8051;
    }
}
