
map $ssl_preread_server_name $targetBackend {
  orderer.blucas-ovh.iparapheur.dev.libriciel.net  orderer;
  peer0.blucas-ovh.iparapheur.dev.libriciel.net    peer0;
  peer1.blucas-ovh.iparapheur.dev.libriciel.net    peer1;
  ca.blucas-ovh.iparapheur.dev.libriciel.net       ca;
}
