

upstream orderer {
  server host.docker.internal:7050;
}

upstream peer0 {
  server host.docker.internal:7051;
}

upstream peer1 {
  server host.docker.internal:8051;
}

upstream ca {
  server host.docker.internal:7054;
}
