
map $ssl_preread_server_name $targetBackend {
  orderer.blucas.iparapheur.dev.libriciel.eu  orderer;
  peer0.blucas.iparapheur.dev.libriciel.eu    peer0;
  peer1.blucas.iparapheur.dev.libriciel.eu    peer1;
  ca.blucas.iparapheur.dev.libriciel.eu       ca;
}
