server:
  port: 8080
  servlet.context-path: /crypto

logging.level.root: INFO

pesv2_sha256:
  policy_id: urn:oid:1.2.250.1.131.1.5.18.21.1.7
  policy_digest: roF9+cfRHNPtVJolhdqfIqGMVuUXX8aR4rpiquf0u5E=
  policy_desc: Politique de signature Helios de la DGFiP
  spuri: https://www.collectivites-locales.gouv.fr/files/files/finances_locales/dematerialisation/ps_helios_dgfip.pdf
