# i-Parapheur Core
# Copyright (C) 2018-2020 Libriciel-SCOP
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

server.servlet.context-path: /api

services:
  content:
    provider: alfresco
    host: alfresco
    port: 8080
    username: admin
    password: admin
    # Generate new ticket every 10 min
    ticket-delay: 600000
  workflow:
    provider: workflow
    host: workflow
    port: 8080
    username: kermit
    password: kermit
    db:
      host: postgres
      port: 5432
      name: flowable
      username: flowable
      password: flowable
  crypto:
    provider: crypto
    host: crypto
    port: 8080
  stats:
    provider: matomo
    host: matomo
    token: ca46afa897d02da9f44bb876360b0017
    port: 80
  pdfstamp:
    provider: pdfstamp
    host: pdf-stamp
    port: 8080
  auth:
    provider: keycloak
    host: keycloak
    port: 8080
    # Generate new ticket every 10 min
    ticket-delay: 60000
    realm: api
    username: rest-admin
    password: admin
    db:
      host: postgres
      port: 5432
      name: keycloak
      login: keycloak
      password: keycloak

spring:
  #cache:
  #  type: redis
  #redis:
  #  host: redis
  #  port: 6379
  servlet.multipart:
    maxFileSize: 5GB
    maxRequestSize: 5GB
  datasource:
    url: jdbc:postgresql://postgres:5432/ipcore
    username: ipcore
    password: ipcore
  jpa:
    # Dialect is hardcoded to fix an minor bug, that logs a lot: createClob() is not yet implemented.
    # https://vkuzel.com/spring-boot-jpa-hibernate-atomikos-postgresql-exception
    # FIXME : remove those when SpringBoot/PostgreSQL fix those
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialectPostgreSQL9Dialect
    hibernate.ddl-auto: update
  main.allow-bean-definition-overriding: true

keycloak:
  auth-server-url: http://iparapheur.dom.local/auth
  realm: api
  resource: ipcore-api
  bearer-only: true
  # Uniquement nécéssaire si le domaine est différent
  # credentials:
  # secret à récupérer sur l'interface keycloak : Interface Admin > Clients > ipcore-api > Credentials > secret
  # secret: be183ad8-baa3-4cb7-b133-11b12400262b

# Pour l'authentification keycloak via swagger
swagger.oauth2.client-id: ipcore-web

logging.level:
  org.jooq: warn
  coop.libriciel.ipcore: info