@business @circuits-unitaires @folder @proposal
Feature: Création de dossiers pour le paramétrage métier "Circuits unitaires"

    Scenario Outline: Create ${count} "${subtype}" draft folders ${withOrWithout} annex
        * def params =
"""
{
    tenant: '<tenant>',
    desktop: '<desktop>',
    type: '<type>',
    subtype: '<subtype>',
    mainFile: '<mainFile>',
    nameTemplate: '<nameTemplate>'
}
"""
      * api_v1.auth.login('user', 'password')
      * def folders = api_v1.desk.draft.getPayloadMonodoc(params, <count>, <extra>, <start>)
      * api_v1.auth.login('<username>', '<password>')
      * def result = call read('classpath:lib/draft/create-and-send-monodoc-<withOrWithout>-annex.feature') folders

      Examples:
          | tenant             | username | password | desktop    | type  | subtype                       | mainFile                             | nameTemplate                                                     | start! | count! | withOrWithout | extra! |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Cachet serveur                | classpath:files/office/main-1_1.doc  | CAdES - Cachet serveur - monodoc - DOC %counter%                 | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Cachet serveur                | classpath:files/office/main-1_1.docx | CAdES - Cachet serveur - monodoc - DOCX %counter%                | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Cachet serveur                | classpath:files/office/main-1_2.ods  | CAdES - Cachet serveur - monodoc - ODS %counter%                 | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Cachet serveur                | classpath:files/office/main-1_1.odt  | CAdES - Cachet serveur - monodoc - ODT %counter%                 | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Cachet serveur                | classpath:files/pdf/main-1_1.pdf     | CAdES - Cachet serveur - monodoc - PDF %counter%                 | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Cachet serveur                | classpath:files/office/main-1_2.xls  | CAdES - Cachet serveur - monodoc - XLS %counter%                 | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Cachet serveur                | classpath:files/office/main-1_2.xlsx | CAdES - Cachet serveur - monodoc - XLSX %counter%                | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Cachet serveur et metadonnees | classpath:files/office/main-1_1.doc  | CAdES - Cachet serveur et métadonnées - monodoc - DOC %counter%  | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Cachet serveur et metadonnees | classpath:files/office/main-1_1.docx | CAdES - Cachet serveur et métadonnées - monodoc - DOCX %counter% | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Cachet serveur et metadonnees | classpath:files/office/main-1_2.ods  | CAdES - Cachet serveur et métadonnées - monodoc - ODS %counter%  | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Cachet serveur et metadonnees | classpath:files/office/main-1_1.odt  | CAdES - Cachet serveur et métadonnées - monodoc - ODT %counter%  | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Cachet serveur et metadonnees | classpath:files/pdf/main-1_1.pdf     | CAdES - Cachet serveur et métadonnées - monodoc - PDF %counter%  | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Cachet serveur et metadonnees | classpath:files/office/main-1_2.xls  | CAdES - Cachet serveur et métadonnées - monodoc - XLS %counter%  | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Cachet serveur et metadonnees | classpath:files/office/main-1_2.xlsx | CAdES - Cachet serveur et métadonnées - monodoc - XLSX %counter% | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Mail securise                 | classpath:files/office/main-1_1.doc  | CAdES - Mail securise - monodoc - DOC %counter%                  | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Mail securise                 | classpath:files/office/main-1_1.docx | CAdES - Mail securise - monodoc - DOCX %counter%                 | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Mail securise                 | classpath:files/office/main-1_2.ods  | CAdES - Mail securise - monodoc - ODS %counter%                  | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Mail securise                 | classpath:files/office/main-1_1.odt  | CAdES - Mail securise - monodoc - ODT %counter%                  | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Mail securise                 | classpath:files/pdf/main-1_1.pdf     | CAdES - Mail securise - monodoc - PDF %counter%                  | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Mail securise                 | classpath:files/office/main-1_2.xls  | CAdES - Mail securise - monodoc - XLS %counter%                  | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Mail securise et metadonnees  | classpath:files/office/main-1_1.doc  | CAdES - Mail securise et métadonnées - monodoc - DOC %counter%   | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Mail securise et metadonnees  | classpath:files/office/main-1_1.docx | CAdES - Mail securise et métadonnées - monodoc - DOCX %counter%  | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Mail securise et metadonnees  | classpath:files/office/main-1_2.ods  | CAdES - Mail securise et métadonnées - monodoc - ODS %counter%   | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Mail securise et metadonnees  | classpath:files/office/main-1_1.odt  | CAdES - Mail securise et métadonnées - monodoc - ODT %counter%   | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Mail securise et metadonnees  | classpath:files/pdf/main-1_1.pdf     | CAdES - Mail securise et métadonnées - monodoc - PDF %counter%   | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Mail securise et metadonnees  | classpath:files/office/main-1_2.xls  | CAdES - Mail securise et métadonnées - monodoc - XLS %counter%   | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Mail securise et metadonnees  | classpath:files/office/main-1_2.xlsx | CAdES - Mail securise et métadonnées - monodoc - XLSX %counter%  | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Signature                     | classpath:files/office/main-1_1.doc  | CAdES - Signature - monodoc - DOC %counter%                      | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Signature                     | classpath:files/office/main-1_1.docx | CAdES - Signature - monodoc - DOCX %counter%                     | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Signature                     | classpath:files/office/main-1_2.ods  | CAdES - Signature - monodoc - ODS %counter%                      | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Signature                     | classpath:files/office/main-1_1.odt  | CAdES - Signature - monodoc - ODT %counter%                      | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Signature                     | classpath:files/pdf/main-1_1.pdf     | CAdES - Signature - monodoc - PDF %counter%                      | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Signature                     | classpath:files/office/main-1_2.xls  | CAdES - Signature - monodoc - XLS %counter%                      | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Signature                     | classpath:files/office/main-1_2.xlsx | CAdES - Signature - monodoc - XLSX %counter%                     | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Signature et metadonnees      | classpath:files/office/main-1_1.doc  | CAdES - Signature et métadonnées - monodoc - DOC %counter%       | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Signature et metadonnees      | classpath:files/office/main-1_1.docx | CAdES - Signature et métadonnées - monodoc - DOCX %counter%      | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Signature et metadonnees      | classpath:files/office/main-1_2.ods  | CAdES - Signature et métadonnées - monodoc - ODS %counter%       | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Signature et metadonnees      | classpath:files/office/main-1_1.odt  | CAdES - Signature et métadonnées - monodoc - ODT %counter%       | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Signature et metadonnees      | classpath:files/pdf/main-1_1.pdf     | CAdES - Signature et métadonnées - monodoc - PDF %counter%       | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Signature et metadonnees      | classpath:files/office/main-1_2.xls  | CAdES - Signature et métadonnées - monodoc - XLS %counter%       | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Signature et metadonnees      | classpath:files/office/main-1_2.xlsx | CAdES - Signature et métadonnées - monodoc - XLSX %counter%      | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Visa                          | classpath:files/office/main-1_1.doc  | CAdES - Visa - monodoc - DOC %counter%                           | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Visa                          | classpath:files/office/main-1_1.docx | CAdES - Visa - monodoc - DOCX %counter%                          | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Visa                          | classpath:files/office/main-1_2.ods  | CAdES - Visa - monodoc - ODS %counter%                           | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Visa                          | classpath:files/office/main-1_1.odt  | CAdES - Visa - monodoc - ODT %counter%                           | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Visa                          | classpath:files/pdf/main-1_1.pdf     | CAdES - Visa - monodoc - PDF %counter%                           | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Visa                          | classpath:files/office/main-1_2.xls  | CAdES - Visa - monodoc - XLS %counter%                           | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Visa                          | classpath:files/office/main-1_2.xlsx | CAdES - Visa - monodoc - XLSX %counter%                          | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Visa et metadonnees           | classpath:files/office/main-1_1.doc  | CAdES - Visa et métadonnées - monodoc - DOC %counter%            | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Visa et metadonnees           | classpath:files/office/main-1_1.docx | CAdES - Visa et métadonnées - monodoc - DOCX %counter%           | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Visa et metadonnees           | classpath:files/office/main-1_2.ods  | CAdES - Visa et métadonnées - monodoc - ODS %counter%            | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Visa et metadonnees           | classpath:files/office/main-1_1.odt  | CAdES - Visa et métadonnées - monodoc - ODT %counter%            | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Visa et metadonnees           | classpath:files/pdf/main-1_1.pdf     | CAdES - Visa et métadonnées - monodoc - PDF %counter%            | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Visa et metadonnees           | classpath:files/office/main-1_2.xls  | CAdES - Visa et métadonnées - monodoc - XLS %counter%            | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | CAdES | Visa et metadonnees           | classpath:files/office/main-1_2.xlsx | CAdES - Visa et métadonnées - monodoc - XLSX %counter%           | 1      | 4      | without       | {}     |
          | Circuits unitaires | ws-cu    | a123456  | WebService | PAdES | Cachet serveur                | classpath:files/pdf/main-1_1.pdf     | PAdES - Cachet serveur - monodoc - PDF %counter%                 | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | PAdES | Cachet serveur et metadonnees | classpath:files/pdf/main-1_1.pdf     | PAdES - Cachet serveur et métadonnées - monodoc - PDF %counter%  | 1      | 4      | without       | {}     |
          | Circuits unitaires | ws-cu    | a123456  | WebService | PAdES | Mail securise                 | classpath:files/pdf/main-1_1.pdf     | PAdES - Mail securise - monodoc - PDF %counter%                  | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | PAdES | Mail securise et metadonnees  | classpath:files/pdf/main-1_1.pdf     | PAdES - Mail securise et métadonnées - monodoc - PDF %counter%   | 1      | 4      | without       | {}     |
          | Circuits unitaires | ws-cu    | a123456  | WebService | PAdES | Signature                     | classpath:files/pdf/main-1_1.pdf     | PAdES - Signature - monodoc - PDF %counter%                      | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | PAdES | Signature et metadonnees      | classpath:files/pdf/main-1_1.pdf     | PAdES - Signature et métadonnées - monodoc - PDF %counter%       | 1      | 4      | without       | {}     |
          | Circuits unitaires | ws-cu    | a123456  | WebService | PAdES | Visa                          | classpath:files/pdf/main-1_1.pdf     | PAdES - Visa - monodoc - PDF %counter%                           | 1      | 4      | without       | {}     |
#          | Circuits unitaires | ws-cu    | a123456  | WebService | PAdES | Visa et metadonnees           | classpath:files/pdf/main-1_1.pdf     | PAdES - Visa et métadonnées - monodoc - PDF %counter%            | 1      | 4      | without       | {}     |
