@provisioning @multi-type-entity
Feature: creation en masse de type

  Background:
    # * configure driver = ip.ui.driver.configure
    * driver baseUrl + ip5.ui.url.logout
    * waitFor('#kc-logout').click()


#  Scenario: Enregistrement de la frequence de notification pour le superadmin
#    * ip5.api.v1.auth.login("user", adminUserPwd)
#    * ip5.api.v1.user.updateCurrentUserNotificationFrequency('none')


  @create-entity
  Scenario: Créer une entité
    * ip5.ui.user.login("user", adminUserPwd)
    * call read('classpath:lib/ip5/ui/tenant/create.feature') { tenant: "multiType" }


#  @create-user
#  Scenario Outline: Créer un utilisateur ${role} et connexion avec celui-ci
#    * ip5.ui.user.login("user", adminUserPwd)
#    * call read('classpath:lib/ip5/ui/user/create.feature') __row
#    * ip5.ui.user.logout()
#    * ip5.ui.user.login(username, password)
#
#    Examples:
#      | tenant      | username                 | lastName  | firstName | email                    | password | role                    |
#      | multiType | jdoe@multiType   | Doe  | John  | jdoe@dom.local | a123456a123456  | Aucun privilège        |


  Scenario Outline: Créer un bureau ${title} pour ${description} utilisateur sans droit
    * ip5.ui.user.login("user", adminUserPwd)
    * call read('classpath:lib/ip5/ui/desk/create.feature') __row

    Examples:
      | tenant      | title      | shortName  | owners!              | permissions!                                                                             | associatedDesks! | description!            |
      | multiType   | DGS        | DGS        | ['jdoe@multiType']   | ['Créer des dossiers','Traiter des dossiers', 'Traiter des dossiers en fin de circuit']  | []               | utilisateur sans droit  |

  Scenario Outline: Créer un circuit 1 étape de ${type} du bureau ${desk}
    * ip5.ui.user.login("user", adminUserPwd)
    * call read('classpath:lib/ip5/ui/workflow/create_1_step.feature') __row

    Examples:
      | tenant      | name      | type      | desk      |
      | multiType   | Signature | Signature | Président |
      | multiType   | Visa      | Visa      | Président |



    @create-types
  Scenario Outline: Créer un type ${name}
    * ip5.api.v1.auth.login('user', adminUserPwd)
    * call read('classpath:lib/ip5/api/setup/type.create.feature') __row

    Examples:

      | tenant    | name  | description       | protocol | signatureFormat | signatureLocation | signatureZipCode | signatureVisible! | signaturePosition!       |
      | multiType | type0 | type0             |          | PADES           |                   |                  | false             |                          |
      | multiType | type1 | type1             |          | PADES           |                   |                  | false             |                          |
      | multiType | type2 | type2             |          | PADES           |                   |                  | false             |                          |
      | multiType | type3 | type3             |          | PADES           |                   |                  | false             |                          |
      | multiType | type4 | type4             |          | PADES           |                   |                  | false             |                          |
      | multiType | type5 | type5             |          | PADES           |                   |                  | false             |                          |
      | multiType | type6 | type6             |          | PADES           |                   |                  | false             |                          |
      | multiType | type7 | type7             |          | PADES           |                   |                  | false             |                          |
      | multiType | type8 | type8             |          | PADES           |                   |                  | false             |                          |
      | multiType | type9 | type9             |          | PADES           |                   |                  | false             |                          |
      | multiType | type10 | type10             |          | PADES           |                   |                  | false             |                          |
      | multiType | type11 | type11             |          | PADES           |                   |                  | false             |                          |
      | multiType | type12 | type12             |          | PADES           |                   |                  | false             |                          |
      | multiType | type13 | type13             |          | PADES           |                   |                  | false             |                          |
      | multiType | type14 | type14             |          | PADES           |                   |                  | false             |                          |
      | multiType | type15 | type15             |          | PADES           |                   |                  | false             |                          |
      | multiType | type16 | type16             |          | PADES           |                   |                  | false             |                          |
      | multiType | type17 | type17             |          | PADES           |                   |                  | false             |                          |
      | multiType | type18 | type18             |          | PADES           |                   |                  | false             |                          |
      | multiType | type19 | type19             |          | PADES           |                   |                  | false             |                          |
      | multiType | type20 | type20             |          | PADES           |                   |                  | false             |                          |
      | multiType | type21 | type21             |          | PADES           |                   |                  | false             |                          |
      | multiType | type22 | type22             |          | PADES           |                   |                  | false             |                          |
      | multiType | type23 | type23             |          | PADES           |                   |                  | false             |                          |
      | multiType | type24 | type24             |          | PADES           |                   |                  | false             |                          |
      | multiType | type25 | type25             |          | PADES           |                   |                  | false             |                          |
      | multiType | type26 | type26             |          | PADES           |                   |                  | false             |                          |
      | multiType | type27 | type27             |          | PADES           |                   |                  | false             |                          |
      | multiType | type28 | type28             |          | PADES           |                   |                  | false             |                          |
      | multiType | type29 | type29             |          | PADES           |                   |                  | false             |                          |
      | multiType | type30 | type30             |          | PADES           |                   |                  | false             |                          |
      | multiType | type31 | type31             |          | PADES           |                   |                  | false             |                          |
      | multiType | type32 | type32             |          | PADES           |                   |                  | false             |                          |
      | multiType | type33 | type33             |          | PADES           |                   |                  | false             |                          |
      | multiType | type34 | type34             |          | PADES           |                   |                  | false             |                          |
      | multiType | type35 | type35             |          | PADES           |                   |                  | false             |                          |
      | multiType | type36 | type36             |          | PADES           |                   |                  | false             |                          |
      | multiType | type37 | type37             |          | PADES           |                   |                  | false             |                          |
      | multiType | type38 | type38             |          | PADES           |                   |                  | false             |                          |
      | multiType | type39 | type39             |          | PADES           |                   |                  | false             |                          |
      | multiType | type40 | type40             |          | PADES           |                   |                  | false             |                          |
      | multiType | type41 | type41             |          | PADES           |                   |                  | false             |                          |
      | multiType | type42 | type42             |          | PADES           |                   |                  | false             |                          |
      | multiType | type43 | type43             |          | PADES           |                   |                  | false             |                          |
      | multiType | type44 | type44             |          | PADES           |                   |                  | false             |                          |
      | multiType | type45 | type45             |          | PADES           |                   |                  | false             |                          |
      | multiType | type46 | type46             |          | PADES           |                   |                  | false             |                          |
      | multiType | type47 | type47             |          | PADES           |                   |                  | false             |                          |
      | multiType | type48 | type48             |          | PADES           |                   |                  | false             |                          |
      | multiType | type49 | type49             |          | PADES           |                   |                  | false             |                          |
      | multiType | type50 | type50             |          | PADES           |                   |                  | false             |                          |
      | multiType | type51 | type51             |          | PADES           |                   |                  | false             |                          |
      | multiType | type52 | type52             |          | PADES           |                   |                  | false             |                          |
      | multiType | type53 | type53             |          | PADES           |                   |                  | false             |                          |
      | multiType | type54 | type54             |          | PADES           |                   |                  | false             |                          |
      | multiType | type55 | type55             |          | PADES           |                   |                  | false             |                          |
      | multiType | type56 | type56             |          | PADES           |                   |                  | false             |                          |
      | multiType | type57 | type57             |          | PADES           |                   |                  | false             |                          |
      | multiType | type58 | type58             |          | PADES           |                   |                  | false             |                          |
      | multiType | type59 | type59             |          | PADES           |                   |                  | false             |                          |
      | multiType | type60 | type60             |          | PADES           |                   |                  | false             |                          |
      | multiType | type61 | type61             |          | PADES           |                   |                  | false             |                          |
      | multiType | type62 | type62             |          | PADES           |                   |                  | false             |                          |
      | multiType | type63 | type63             |          | PADES           |                   |                  | false             |                          |
      | multiType | type64 | type64             |          | PADES           |                   |                  | false             |                          |
      | multiType | type65 | type65             |          | PADES           |                   |                  | false             |                          |
      | multiType | type66 | type66             |          | PADES           |                   |                  | false             |                          |
      | multiType | type67 | type67             |          | PADES           |                   |                  | false             |                          |
      | multiType | type68 | type68             |          | PADES           |                   |                  | false             |                          |
      | multiType | type69 | type69             |          | PADES           |                   |                  | false             |                          |
      | multiType | type70 | type70             |          | PADES           |                   |                  | false             |                          |
      | multiType | type71 | type71             |          | PADES           |                   |                  | false             |                          |
      | multiType | type72 | type72             |          | PADES           |                   |                  | false             |                          |
      | multiType | type73 | type73             |          | PADES           |                   |                  | false             |                          |
      | multiType | type74 | type74             |          | PADES           |                   |                  | false             |                          |
      | multiType | type75 | type75             |          | PADES           |                   |                  | false             |                          |
      | multiType | type76 | type76             |          | PADES           |                   |                  | false             |                          |
      | multiType | type77 | type77             |          | PADES           |                   |                  | false             |                          |
      | multiType | type78 | type78             |          | PADES           |                   |                  | false             |                          |
      | multiType | type79 | type79             |          | PADES           |                   |                  | false             |                          |
      | multiType | type80 | type80             |          | PADES           |                   |                  | false             |                          |
      | multiType | type81 | type81             |          | PADES           |                   |                  | false             |                          |
      | multiType | type82 | type82             |          | PADES           |                   |                  | false             |                          |
      | multiType | type83 | type83             |          | PADES           |                   |                  | false             |                          |
      | multiType | type84 | type84             |          | PADES           |                   |                  | false             |                          |
      | multiType | type85 | type85             |          | PADES           |                   |                  | false             |                          |
      | multiType | type86 | type86             |          | PADES           |                   |                  | false             |                          |
      | multiType | type87 | type87             |          | PADES           |                   |                  | false             |                          |
      | multiType | type88 | type88             |          | PADES           |                   |                  | false             |                          |
      | multiType | type89 | type89             |          | PADES           |                   |                  | false             |                          |
      | multiType | type90 | type90             |          | PADES           |                   |                  | false             |                          |
      | multiType | type91 | type91             |          | PADES           |                   |                  | false             |                          |
      | multiType | type92 | type92             |          | PADES           |                   |                  | false             |                          |
      | multiType | type93 | type93             |          | PADES           |                   |                  | false             |                          |
      | multiType | type94 | type94             |          | PADES           |                   |                  | false             |                          |
      | multiType | type95 | type95             |          | PADES           |                   |                  | false             |                          |
      | multiType | type96 | type96             |          | PADES           |                   |                  | false             |                          |
      | multiType | type97 | type97             |          | PADES           |                   |                  | false             |                          |
      | multiType | type98 | type98             |          | PADES           |                   |                  | false             |                          |
      | multiType | type99 | type99             |          | PADES           |                   |                  | false             |                          |
      | multiType | type100 | type100             |          | PADES           |                   |                  | false             |                          |
      | multiType | type101 | type101             |          | PADES           |                   |                  | false             |                          |
      | multiType | type102 | type102             |          | PADES           |                   |                  | false             |                          |
      | multiType | type103 | type103             |          | PADES           |                   |                  | false             |                          |
      | multiType | type104 | type104             |          | PADES           |                   |                  | false             |                          |
      | multiType | type105 | type105             |          | PADES           |                   |                  | false             |                          |
      | multiType | type106 | type106             |          | PADES           |                   |                  | false             |                          |
      | multiType | type107 | type107             |          | PADES           |                   |                  | false             |                          |
      | multiType | type108 | type108             |          | PADES           |                   |                  | false             |                          |
      | multiType | type109 | type109             |          | PADES           |                   |                  | false             |                          |







      @create-subtypes
  Scenario Outline: Créer un sous-type ${type} / ${name} pour le circuit ${validationWorkflowId}
      * ip5.api.v1.auth.login('user', adminUserPwd)
      * call read('classpath:lib/ip5/api/setup/subtype.create.feature') __row


    Examples:

      | tenant    | type   | name       | annotationsAllowed! | multiDocuments! | creationPermittedDeskIds! | creationWorkflowId | validationWorkflowId | externalSignatureConfigId | sealAutomatic! | sealCertificateId                                  | secureMailServerId | digitalSignatureMandatory! | workflowSelectionScript! | subtypeLayerList! | subtypeMetadataList!                                                                         | multiDocuments! |
      | multiType | type0  | subtype0-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type0  | subtype0-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type1  | subtype1-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type2  | subtype2-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type3  | subtype3-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type4  | subtype4-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type5  | subtype5-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type6  | subtype6-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type7  | subtype7-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type8  | subtype8-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type9  | subtype9-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type10  | subtype10-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type11  | subtype11-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type12  | subtype12-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type13  | subtype13-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type14  | subtype14-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type15  | subtype15-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type16  | subtype16-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type17  | subtype17-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type18  | subtype18-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type19  | subtype19-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type20  | subtype20-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type21  | subtype21-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type22  | subtype22-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type23  | subtype23-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type24  | subtype24-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type25  | subtype25-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type26  | subtype26-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type27  | subtype27-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type28  | subtype28-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type29  | subtype29-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type30  | subtype30-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type31  | subtype31-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type32  | subtype32-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type33  | subtype33-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type34  | subtype34-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type35  | subtype35-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type36  | subtype36-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type37  | subtype37-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type38  | subtype38-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type39  | subtype39-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type40  | subtype40-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type41  | subtype41-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type42  | subtype42-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type43  | subtype43-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type44  | subtype44-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type45  | subtype45-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type46  | subtype46-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type47  | subtype47-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type48  | subtype48-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type49  | subtype49-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type50  | subtype50-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type51  | subtype51-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type52  | subtype52-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type53  | subtype53-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type54  | subtype54-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type55  | subtype55-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type56  | subtype56-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type57  | subtype57-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type58  | subtype58-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type59  | subtype59-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type60  | subtype60-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type61  | subtype61-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type62  | subtype62-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type63  | subtype63-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type64  | subtype64-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type65  | subtype65-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type66  | subtype66-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type67  | subtype67-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type68  | subtype68-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type69  | subtype69-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type70  | subtype70-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type71  | subtype71-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type72  | subtype72-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type73  | subtype73-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type74  | subtype74-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type75  | subtype75-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type76  | subtype76-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type77  | subtype77-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type78  | subtype78-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type79  | subtype79-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type80  | subtype80-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type81  | subtype81-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type82  | subtype82-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type83  | subtype83-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type84  | subtype84-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type85  | subtype85-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type86  | subtype86-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type87  | subtype87-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type88  | subtype88-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type89  | subtype89-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type90  | subtype90-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type91  | subtype91-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type92  | subtype92-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type93  | subtype93-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type94  | subtype94-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type95  | subtype95-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type96  | subtype96-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type97  | subtype97-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type98  | subtype98-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type99  | subtype99-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type100  | subtype100-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type101  | subtype101-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type102  | subtype102-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type103  | subtype103-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type104  | subtype104-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type105  | subtype105-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type106  | subtype106-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type107  | subtype107-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type108  | subtype108-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |
      | multiType | type109  | subtype109-1 | false               | false           | []                        |                    | Visa                 |                           | null           |                                                    |                    | true                       |                          | []                | []                                                                                           | false           |

