@business @formats-de-signature @folder @proposal @wip
Feature: Création de dossiers pour le paramétrage métier "Formats de signature"

    Scenario Outline: Create ${count} "${subtype}" draft folders ${withOrWithout} annex
        * def params =
"""
{
    tenant: 'Formats de signature',
    desktop: 'WebService',
    type: '<type>',
    subtype: '<subtype>',
    mainFile: <mainFile>,
    nameTemplate: '<nameTemplate>'
}
"""
        * api_v1.auth.login('user', 'password')
        * def folders = api_v1.desk.draft.getPayloadMonodoc(params, <count>, <extra>, <start>)
        * api_v1.auth.login('ws-fds', 'a123456')
        * def result = call read('classpath:lib/draft/create-and-send-monodoc-<withOrWithout>-annex.feature') folders

        # @todo (ailleurs): mainFile -> mainFile!
        Examples:
            | type               | subtype        | mainFile!                                                                                                                | nameTemplate                                                                                      | start! | count! | withOrWithout | extra! |
            | ACTES - CAdES      | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': null}                                                  | ACTES - CAdES - Signature - monodoc - PDF_sans_tags - %counter%                                   | 1      | 1      | without       | {}     |
            | ACTES - CAdES      | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': 'classpath:files/formats/signature_cades.p7s'}         | ACTES - CAdES - Signature - monodoc - PDF_sans_tags - signe_cades - %counter%                     | 1      | 1      | without       | {}     |
            | ACTES - CAdES      | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': 'classpath:files/formats/signature_xades.xml'}         | ACTES - CAdES - Signature - monodoc - PDF_sans_tags - signe_xades - %counter%                     | 1      | 1      | without       | {}     |
            | ACTES - CAdES      | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': null}                                                  | ACTES - CAdES - Signature - monodoc - PDF_avec_tags - %counter%                                   | 1      | 1      | without       | {}     |
            | ACTES - CAdES      | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': 'classpath:files/formats/signature_cades.p7s'}         | ACTES - CAdES - Signature - monodoc - PDF_avec_tags - signe_cades - %counter%                     | 1      | 1      | without       | {}     |
            | ACTES - CAdES      | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': 'classpath:files/formats/signature_xades.xml'}         | ACTES - CAdES - Signature - monodoc - PDF_avec_tags - signe_xades - %counter%                     | 1      | 1      | without       | {}     |
            | ACTES - CAdES      | Signature      | {'file': 'classpath:files/formats/document_libre_office.odt', 'detached': null}                                          | ACTES - CAdES - Signature - monodoc - ODT - %counter%                                             | 1      | 1      | without       | {}     |
            | ACTES - CAdES      | Signature      | {'file': 'classpath:files/formats/document_libre_office.odt', 'detached': 'classpath:files/formats/signature_cades.p7s'} | ACTES - CAdES - Signature - monodoc - ODT - signe_cades - %counter%                               | 1      | 1      | without       | {}     |
            | ACTES - CAdES      | Signature      | {'file': 'classpath:files/formats/document_libre_office.odt', 'detached': 'classpath:files/formats/signature_xades.xml'} | ACTES - CAdES - Signature - monodoc - ODT - signe_xades - %counter%                               | 1      | 1      | without       | {}     |
            | ACTES - CAdES      | Signature      | {'file': 'classpath:files/formats/document_office.doc', 'detached': null}                                                | ACTES - CAdES - Signature - monodoc - DOC - %counter%                                             | 1      | 1      | without       | {}     |
            | ACTES - CAdES      | Signature      | {'file': 'classpath:files/formats/document_office.doc', 'detached': 'classpath:files/formats/signature_cades.p7s'}       | ACTES - CAdES - Signature - monodoc - DOC - signe_cades - %counter%                               | 1      | 1      | without       | {}     |
            | ACTES - CAdES      | Signature      | {'file': 'classpath:files/formats/document_office.doc', 'detached': 'classpath:files/formats/signature_xades.xml'}       | ACTES - CAdES - Signature - monodoc - DOC - signe_xades - %counter%                               | 1      | 1      | without       | {}     |
            | ACTES - PAdES      | Cachet serveur | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': null}                                                  | ACTES - PAdES - Cachet serveur - monodoc - PDF_sans_tags - %counter%                              | 1      | 1      | without       | {}     |
            | ACTES - PAdES      | Cachet serveur | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': null}                                                  | ACTES - PAdES - Cachet serveur - monodoc - PDF_sans_tags - repositionnement signature - %counter% | 1      | 1      | without       | {}     |
            | ACTES - PAdES      | Cachet serveur | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': 'classpath:files/formats/signature_cades.p7s'}         | ACTES - PAdES - Cachet serveur - monodoc - PDF_sans_tags - signe_cades - %counter%                | 1      | 1      | without       | {}     |
            | ACTES - PAdES      | Cachet serveur | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': 'classpath:files/formats/signature_xades.xml'}         | ACTES - PAdES - Cachet serveur - monodoc - PDF_sans_tags - signe_xades - %counter%                | 1      | 1      | without       | {}     |
            | ACTES - PAdES      | Cachet serveur | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': null}                                                  | ACTES - PAdES - Cachet serveur - monodoc - PDF_avec_tags - %counter%                              | 1      | 1      | without       | {}     |
            | ACTES - PAdES      | Cachet serveur | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': null}                                                  | ACTES - PAdES - Cachet serveur - monodoc - PDF_avec_tags - repositionnement signature - %counter% | 1      | 1      | without       | {}     |
            | ACTES - PAdES      | Cachet serveur | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': 'classpath:files/formats/signature_cades.p7s'}         | ACTES - PAdES - Cachet serveur - monodoc - PDF_avec_tags - signe_cades - %counter%                | 1      | 1      | without       | {}     |
            | ACTES - PAdES      | Cachet serveur | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': 'classpath:files/formats/signature_xades.xml'}         | ACTES - PAdES - Cachet serveur - monodoc - PDF_avec_tags - signe_xades - %counter%                | 1      | 1      | without       | {}     |
            | ACTES - PAdES      | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': null}                                                  | ACTES - PAdES - Signature - monodoc - PDF_sans_tags - %counter%                                   | 1      | 1      | without       | {}     |
            | ACTES - PAdES      | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': null}                                                  | ACTES - PAdES - Signature - monodoc - PDF_sans_tags - repositionnement signature - %counter%      | 1      | 1      | without       | {}     |
            | ACTES - PAdES      | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': 'classpath:files/formats/signature_cades.p7s'}         | ACTES - PAdES - Signature - monodoc - PDF_sans_tags - signe_cades - %counter%                     | 1      | 1      | without       | {}     |
            | ACTES - PAdES      | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': 'classpath:files/formats/signature_xades.xml'}         | ACTES - PAdES - Signature - monodoc - PDF_sans_tags - signe_xades - %counter%                     | 1      | 1      | without       | {}     |
            | ACTES - PAdES      | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': null}                                                  | ACTES - PAdES - Signature - monodoc - PDF_avec_tags - %counter%                                   | 1      | 1      | without       | {}     |
            | ACTES - PAdES      | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': null}                                                  | ACTES - PAdES - Signature - monodoc - PDF_avec_tags - repositionnement signature - %counter%      | 1      | 1      | without       | {}     |
            | ACTES - PAdES      | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': 'classpath:files/formats/signature_cades.p7s'}         | ACTES - PAdES - Signature - monodoc - PDF_avec_tags - signe_cades - %counter%                     | 1      | 1      | without       | {}     |
            | ACTES - PAdES      | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': 'classpath:files/formats/signature_xades.xml'}         | ACTES - PAdES - Signature - monodoc - PDF_avec_tags - signe_xades - %counter%                     | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': null}                                                  | Automatique - Signature - monodoc - PDF_sans_tags - %counter%                                     | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': 'classpath:files/formats/signature_cades.p7s'}         | Automatique - Signature - monodoc - PDF_sans_tags - signe_cades - %counter%                       | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': 'classpath:files/formats/signature_xades.xml'}         | Automatique - Signature - monodoc - PDF_sans_tags - signe_xades - %counter%                       | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': null}                                                  | Automatique - Signature - monodoc - PDF_avec_tags - %counter%                                     | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': 'classpath:files/formats/signature_cades.p7s'}         | Automatique - Signature - monodoc - PDF_avec_tags - signe_cades - %counter%                       | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': 'classpath:files/formats/signature_xades.xml'}         | Automatique - Signature - monodoc - PDF_avec_tags - signe_xades - %counter%                       | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | {'file': 'classpath:files/formats/document_libre_office.odt', 'detached': null}                                          | Automatique - Signature - monodoc - ODT - %counter%                                               | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | {'file': 'classpath:files/formats/document_libre_office.odt', 'detached': 'classpath:files/formats/signature_cades.p7s'} | Automatique - Signature - monodoc - ODT - signe_cades - %counter%                                 | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | {'file': 'classpath:files/formats/document_libre_office.odt', 'detached': 'classpath:files/formats/signature_xades.xml'} | Automatique - Signature - monodoc - ODT - signe_xades - %counter%                                 | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | {'file': 'classpath:files/formats/document_office.doc', 'detached': null}                                                | Automatique - Signature - monodoc - DOC - %counter%                                               | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | {'file': 'classpath:files/formats/document_office.doc', 'detached': 'classpath:files/formats/signature_cades.p7s'}       | Automatique - Signature - monodoc - DOC - signe_cades - %counter%                                 | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | {'file': 'classpath:files/formats/document_office.doc', 'detached': 'classpath:files/formats/signature_xades.xml'}       | Automatique - Signature - monodoc - DOC - signe_xades - %counter%                                 | 1      | 1      | without       | {}     |
            | CAdES              | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': null}                                                  | CAdES - Signature - monodoc - PDF_sans_tags - %counter%                                           | 1      | 1      | without       | {}     |
            | CAdES              | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': 'classpath:files/formats/signature_cades.p7s'}         | CAdES - Signature - monodoc - PDF_sans_tags - signe_cades - %counter%                             | 1      | 1      | without       | {}     |
            | CAdES              | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': 'classpath:files/formats/signature_xades.xml'}         | CAdES - Signature - monodoc - PDF_sans_tags - signe_xades - %counter%                             | 1      | 1      | without       | {}     |
            | CAdES              | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': null}                                                  | CAdES - Signature - monodoc - PDF_avec_tags - %counter%                                           | 1      | 1      | without       | {}     |
            | CAdES              | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': 'classpath:files/formats/signature_cades.p7s'}         | CAdES - Signature - monodoc - PDF_avec_tags - signe_cades - %counter%                             | 1      | 1      | without       | {}     |
            | CAdES              | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': 'classpath:files/formats/signature_xades.xml'}         | CAdES - Signature - monodoc - PDF_avec_tags - signe_xades - %counter%                             | 1      | 1      | without       | {}     |
            | CAdES              | Signature      | {'file': 'classpath:files/formats/document_libre_office.odt', 'detached': null}                                          | CAdES - Signature - monodoc - ODT - %counter%                                                     | 1      | 1      | without       | {}     |
            | CAdES              | Signature      | {'file': 'classpath:files/formats/document_libre_office.odt', 'detached': 'classpath:files/formats/signature_cades.p7s'} | CAdES - Signature - monodoc - ODT - signe_cades - %counter%                                       | 1      | 1      | without       | {}     |
            | CAdES              | Signature      | {'file': 'classpath:files/formats/document_libre_office.odt', 'detached': 'classpath:files/formats/signature_xades.xml'} | CAdES - Signature - monodoc - ODT - signe_xades - %counter%                                       | 1      | 1      | without       | {}     |
            | CAdES              | Signature      | {'file': 'classpath:files/formats/document_office.doc', 'detached': null}                                                | CAdES - Signature - monodoc - DOC - %counter%                                                     | 1      | 1      | without       | {}     |
            | CAdES              | Signature      | {'file': 'classpath:files/formats/document_office.doc', 'detached': 'classpath:files/formats/signature_cades.p7s'}       | CAdES - Signature - monodoc - DOC - signe_cades - %counter%                                       | 1      | 1      | without       | {}     |
            | CAdES              | Signature      | {'file': 'classpath:files/formats/document_office.doc', 'detached': 'classpath:files/formats/signature_xades.xml'}       | CAdES - Signature - monodoc - DOC - signe_xades - %counter%                                       | 1      | 1      | without       | {}     |
            | HELIOS - XAdES env | Signature      | 'classpath:files/xml/PESALR1_unsigned.xml'                                                                               | HELIOS - XAdES env - Signature - monodoc - XML %counter%                                          | 1      | 1      | without       | {}     |
            | PAdES              | Cachet serveur | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': null}                                                  | PAdES - Cachet serveur - monodoc - PDF_sans_tags - %counter%                                      | 1      | 1      | without       | {}     |
            | PAdES              | Cachet serveur | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': null}                                                  | PAdES - Cachet serveur - monodoc - PDF_sans_tags - repositionnement signature - %counter%         | 1      | 1      | without       | {}     |
            | PAdES              | Cachet serveur | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': 'classpath:files/formats/signature_cades.p7s'}         | PAdES - Cachet serveur - monodoc - PDF_sans_tags - signe_cades - %counter%                        | 1      | 1      | without       | {}     |
            | PAdES              | Cachet serveur | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': 'classpath:files/formats/signature_xades.xml'}         | PAdES - Cachet serveur - monodoc - PDF_sans_tags - signe_xades - %counter%                        | 1      | 1      | without       | {}     |
            | PAdES              | Cachet serveur | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': null}                                                  | PAdES - Cachet serveur - monodoc - PDF_avec_tags - %counter%                                      | 1      | 1      | without       | {}     |
            | PAdES              | Cachet serveur | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': null}                                                  | PAdES - Cachet serveur - monodoc - PDF_avec_tags - repositionnement signature - %counter%         | 1      | 1      | without       | {}     |
            | PAdES              | Cachet serveur | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': 'classpath:files/formats/signature_cades.p7s'}         | PAdES - Cachet serveur - monodoc - PDF_avec_tags - signe_cades - %counter%                        | 1      | 1      | without       | {}     |
            | PAdES              | Cachet serveur | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': 'classpath:files/formats/signature_xades.xml'}         | PAdES - Cachet serveur - monodoc - PDF_avec_tags - signe_xades - %counter%                        | 1      | 1      | without       | {}     |
            | PAdES              | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': null}                                                  | PAdES - Signature - monodoc - PDF_sans_tags - %counter%                                           | 1      | 1      | without       | {}     |
            | PAdES              | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': null}                                                  | PAdES - Signature - monodoc - PDF_sans_tags - repositionnement signature - %counter%              | 1      | 1      | without       | {}     |
            | PAdES              | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': 'classpath:files/formats/signature_cades.p7s'}         | PAdES - Signature - monodoc - PDF_sans_tags - signe_cades - %counter%                             | 1      | 1      | without       | {}     |
            | PAdES              | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': 'classpath:files/formats/signature_xades.xml'}         | PAdES - Signature - monodoc - PDF_sans_tags - signe_xades - %counter%                             | 1      | 1      | without       | {}     |
            | PAdES              | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': null}                                                  | PAdES - Signature - monodoc - PDF_avec_tags - %counter%                                           | 1      | 1      | without       | {}     |
            | PAdES              | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': null}                                                  | PAdES - Signature - monodoc - PDF_avec_tags - repositionnement signature - %counter%              | 1      | 1      | without       | {}     |
            | PAdES              | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': 'classpath:files/formats/signature_cades.p7s'}         | PAdES - Signature - monodoc - PDF_avec_tags - signe_cades - %counter%                             | 1      | 1      | without       | {}     |
            | PAdES              | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': 'classpath:files/formats/signature_xades.xml'}         | PAdES - Signature - monodoc - PDF_avec_tags - signe_xades - %counter%                             | 1      | 1      | without       | {}     |
            | XAdES det          | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': null}                                                  | XAdES det - Signature - monodoc - PDF_sans_tags - %counter%                                       | 1      | 1      | without       | {}     |
            | XAdES det          | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': 'classpath:files/formats/signature_cades.p7s'}         | XAdES det - Signature - monodoc - PDF_sans_tags - signe_cades - %counter%                         | 1      | 1      | without       | {}     |
            | XAdES det          | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags.pdf', 'detached': 'classpath:files/formats/signature_xades.xml'}         | XAdES det - Signature - monodoc - PDF_sans_tags - signe_xades - %counter%                         | 1      | 1      | without       | {}     |
            | XAdES det          | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': null}                                                  | XAdES det - Signature - monodoc - PDF_avec_tags - %counter%                                       | 1      | 1      | without       | {}     |
            | XAdES det          | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': 'classpath:files/formats/signature_cades.p7s'}         | XAdES det - Signature - monodoc - PDF_avec_tags - signe_cades - %counter%                         | 1      | 1      | without       | {}     |
            | XAdES det          | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags.pdf', 'detached': 'classpath:files/formats/signature_xades.xml'}         | XAdES det - Signature - monodoc - PDF_avec_tags - signe_xades - %counter%                         | 1      | 1      | without       | {}     |
            | XAdES det          | Signature      | {'file': 'classpath:files/formats/document_libre_office.odt', 'detached': null}                                          | XAdES det - Signature - monodoc - ODT - %counter%                                                 | 1      | 1      | without       | {}     |
            | XAdES det          | Signature      | {'file': 'classpath:files/formats/document_libre_office.odt', 'detached': 'classpath:files/formats/signature_cades.p7s'} | XAdES det - Signature - monodoc - ODT - signe_cades - %counter%                                   | 1      | 1      | without       | {}     |
            | XAdES det          | Signature      | {'file': 'classpath:files/formats/document_libre_office.odt', 'detached': 'classpath:files/formats/signature_xades.xml'} | XAdES det - Signature - monodoc - ODT - signe_xades - %counter%                                   | 1      | 1      | without       | {}     |
            | XAdES det          | Signature      | {'file': 'classpath:files/formats/document_office.doc', 'detached': null}                                                | XAdES det - Signature - monodoc - DOC - %counter%                                                 | 1      | 1      | without       | {}     |
            | XAdES det          | Signature      | {'file': 'classpath:files/formats/document_office.doc', 'detached': 'classpath:files/formats/signature_cades.p7s'}       | XAdES det - Signature - monodoc - DOC - signe_cades - %counter%                                   | 1      | 1      | without       | {}     |
            | XAdES det          | Signature      | {'file': 'classpath:files/formats/document_office.doc', 'detached': 'classpath:files/formats/signature_xades.xml'}       | XAdES det - Signature - monodoc - DOC - signe_xades - %counter%                                   | 1      | 1      | without       | {}     |


#            | ACTES - CAdES      | Signature      | classpath:files/office/main-1_1.doc      | ACTES - CAdES - Signature - monodoc - DOC %counter%      | 1      | 1      | without       | {}     |
#            | ACTES - CAdES      | Signature      | classpath:files/office/main-1_1.odt      | ACTES - CAdES - Signature - monodoc - ODT %counter%      | 1      | 1      | without       | {}     |
#            | ACTES - CAdES      | Signature      | classpath:files/pdf/main-1_1.pdf         | ACTES - CAdES - Signature - monodoc - PDF %counter%      | 1      | 1      | without       | {}     |
#            | ACTES - PAdES      | Cachet serveur | classpath:files/pdf/main-1_1.pdf         | ACTES - PAdES - Cachet serveur - monodoc - PDF %counter% | 1      | 1      | without       | {}     |
#            | ACTES - PAdES      | Signature      | classpath:files/pdf/main-1_1.pdf         | ACTES - PAdES - Signature - monodoc - PDF %counter%      | 1      | 1      | without       | {}     |
#            | Automatique        | Signature      | classpath:files/office/main-1_1.doc      | Automatique - Signature - monodoc - DOC %counter%        | 1      | 1      | without       | {}     |
#            | Automatique        | Signature      | classpath:files/office/main-1_1.odt      | Automatique - Signature - monodoc - ODT %counter%        | 1      | 1      | without       | {}     |
#            | Automatique        | Signature      | classpath:files/pdf/main-1_1.pdf         | Automatique - Signature - monodoc - PDF %counter%        | 1      | 1      | without       | {}     |
#            | CAdES              | Signature      | classpath:files/office/main-1_1.doc      | CAdES - Signature - monodoc - DOC %counter%              | 1      | 1      | without       | {}     |
#            | CAdES              | Signature      | classpath:files/office/main-1_1.odt      | CAdES - Signature - monodoc - ODT %counter%              | 1      | 1      | without       | {}     |
#            | CAdES              | Signature      | classpath:files/pdf/main-1_1.pdf         | CAdES - Signature - monodoc - PDF %counter%              | 1      | 1      | without       | {}     |
#            | HELIOS - XAdES env | Signature      | classpath:files/xml/PESALR1_unsigned.xml | HELIOS - XAdES env - Signature - monodoc - XML %counter% | 1      | 1      | without       | {}     |
#            | PAdES              | Cachet serveur | classpath:files/pdf/main-1_1.pdf         | PAdES - Cachet serveur - monodoc - PDF %counter%         | 1      | 1      | without       | {}     |
#            | PAdES              | Signature      | classpath:files/pdf/main-1_1.pdf         | PAdES - Signature - monodoc - PDF %counter%              | 1      | 1      | without       | {}     |
#            | XAdES det          | Signature      | classpath:files/office/main-1_1.doc      | XAdES det - Signature - monodoc - DOC %counter%          | 1      | 1      | without       | {}     |
#            | XAdES det          | Signature      | classpath:files/office/main-1_1.odt      | XAdES det - Signature - monodoc - ODT %counter%          | 1      | 1      | without       | {}     |
#            | XAdES det          | Signature      | classpath:files/pdf/main-1_1.pdf         | XAdES det - Signature - monodoc - PDF %counter%          | 1      | 1      | without       | {}     |

            #| ACTES - CAdES      | Signature      | {'file': 'classpath:files/pdf/main-1_1.pdf', 'detached': 'classpath:files/signed/CAdES - signature - PDF/main-1_1.pdf-1-Christian Noir.p7s'}         | ACTES - CAdES - Signature - monodoc - PDF %counter%      | 1      | 1      | without       | {}     |
