@business @formats-de-signature @folder @proposal
Feature: Création de dossiers pour le paramétrage métier "Formats de signature"

    Scenario Outline: Create ${count} "${subtype}" draft folders ${withOrWithout} annex
        * def params =
"""
{
    tenant: 'Formats de signature',
    desktop: 'WebService',
    type: '<type>',
    subtype: '<subtype>',
    mainFile: <mainFile>,
    nameTemplate: '<nameTemplate>'
}
"""
        * api_v1.auth.login('user', 'password')
        * def folders = api_v1.desk.draft.getPayloadMonodoc(params, <count>, <extra>, <start>)
        * api_v1.auth.login('ws-fds', 'a123456')
        * def result = call read('classpath:lib/draft/create-and-send-monodoc-<withOrWithout>-annex.feature') folders

        Examples:
            | type               | subtype        | mainFile!                                                                                                                                                            | nameTemplate                                                           | start! | count! | withOrWithout | extra! |
            | Automatique        | Signature      | 'classpath:files/formats/document_office/document_office.doc',                                                                                                       | Automatique - Signature - DOC                                          | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | {'file': 'classpath:files/formats/document_office/document_office.doc', 'detached': 'classpath:files/formats/document_office/signature_cades.p7s'}                   | Automatique - Signature - DOC - signe_cades                            | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | {'file': 'classpath:files/formats/document_office/document_office.doc', 'detached': 'classpath:files/formats/document_office/signature_xades.xml'}                   | Automatique - Signature - DOC - signe_xades                            | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | 'classpath:files/formats/document_libre_office/document_libre_office.odt',                                                                                           | Automatique - Signature - ODT                                          | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | {'file': 'classpath:files/formats/document_libre_office/document_libre_office.odt', 'detached': 'classpath:files/formats/document_libre_office/signature_cades.p7s'} | Automatique - Signature - ODT - signe_cades                            | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | {'file': 'classpath:files/formats/document_libre_office/document_libre_office.odt', 'detached': 'classpath:files/formats/document_libre_office/signature_xades.xml'} | Automatique - Signature - ODT - signe_xades                            | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | 'classpath:files/formats/PDF_sans_tags/PDF_sans_tags.pdf',                                                                                                           | Automatique - Signature - PDF_sans_tags                                | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | 'classpath:files/formats/PDF_sans_tags/PDF_sans_tags.pdf',                                                                                                           | Automatique - Signature - PDF_sans_tags - repositionnement signature   | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags/PDF_sans_tags.pdf', 'detached': 'classpath:files/formats/PDF_sans_tags/signature_cades.p7s'}                         | Automatique - Signature - PDF_sans_tags - signe_cades                  | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | 'classpath:files/formats/PDF_sans_tags/PDF_sans_tags-signature_pades.pdf',                                                                                           | Automatique - Signature - PDF_sans_tags - signe_pades                  | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags/PDF_sans_tags.pdf', 'detached': 'classpath:files/formats/PDF_sans_tags/signature_xades.xml'}                         | Automatique - Signature - PDF_sans_tags - signe_xades                  | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | 'classpath:files/formats/PDF_avec_tags/PDF_avec_tags.pdf',                                                                                                           | Automatique - Signature - PDF_avec_tags                                | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | 'classpath:files/formats/PDF_avec_tags/PDF_avec_tags.pdf',                                                                                                           | Automatique - Signature - PDF_avec_tags - repositionnement signature   | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags/PDF_avec_tags.pdf', 'detached': 'classpath:files/formats/PDF_avec_tags/signature_cades.p7s'}                         | Automatique - Signature - PDF_avec_tags - signe_cades                  | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | 'classpath:files/formats/PDF_avec_tags/PDF_avec_tags-signature_pades.pdf',                                                                                           | Automatique - Signature - PDF_avec_tags - signe_pades                  | 1      | 1      | without       | {}     |
            | Automatique        | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags/PDF_avec_tags.pdf', 'detached': 'classpath:files/formats/PDF_avec_tags/signature_xades.xml'}                         | Automatique - Signature - PDF_avec_tags - signe_xades                  | 1      | 1      | without       | {}     |
            | CAdES              | Signature      | 'classpath:files/formats/document_office/document_office.doc',                                                                                                       | CAdES - Signature - DOC                                                | 1      | 1      | without       | {}     |
            | CAdES              | Signature      | {'file': 'classpath:files/formats/document_office/document_office.doc', 'detached': 'classpath:files/formats/document_office/signature_cades.p7s'}                   | CAdES - Signature - DOC - signe_cades                                  | 1      | 1      | without       | {}     |
            | CAdES              | Signature      | {'file': 'classpath:files/formats/document_office/document_office.doc', 'detached': 'classpath:files/formats/document_office/signature_xades.xml'}                   | CAdES - Signature - DOC - signe_xades                                  | 1      | 1      | without       | {}     |
            | CAdES              | Signature      | 'classpath:files/formats/document_libre_office/document_libre_office.odt',                                                                                           | CAdES - Signature - ODT                                                | 1      | 1      | without       | {}     |
            | CAdES              | Signature      | {'file': 'classpath:files/formats/document_libre_office/document_libre_office.odt', 'detached': 'classpath:files/formats/document_libre_office/signature_cades.p7s'} | CAdES - Signature - ODT - signe_cades                                  | 1      | 1      | without       | {}     |
            | CAdES              | Signature      | {'file': 'classpath:files/formats/document_libre_office/document_libre_office.odt', 'detached': 'classpath:files/formats/document_libre_office/signature_xades.xml'} | CAdES - Signature - ODT - signe_xades                                  | 1      | 1      | without       | {}     |
            | CAdES              | Signature      | 'classpath:files/formats/PDF_sans_tags/PDF_sans_tags.pdf',                                                                                                           | CAdES - Signature - PDF_sans_tags                                      | 1      | 1      | without       | {}     |
            | CAdES              | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags/PDF_sans_tags.pdf', 'detached': 'classpath:files/formats/PDF_sans_tags/signature_cades.p7s'}                         | CAdES - Signature - PDF_sans_tags - signe_cades                        | 1      | 1      | without       | {}     |
            | CAdES              | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags/PDF_sans_tags.pdf', 'detached': 'classpath:files/formats/PDF_sans_tags/signature_xades.xml'}                         | CAdES - Signature - PDF_sans_tags - signe_xades                        | 1      | 1      | without       | {}     |
            | CAdES              | Signature      | 'classpath:files/formats/PDF_avec_tags/PDF_avec_tags.pdf',                                                                                                           | CAdES - Signature - PDF_avec_tags                                      | 1      | 1      | without       | {}     |
            | CAdES              | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags/PDF_avec_tags.pdf', 'detached': 'classpath:files/formats/PDF_avec_tags/signature_cades.p7s'}                         | CAdES - Signature - PDF_avec_tags - signe_cades                        | 1      | 1      | without       | {}     |
            | CAdES              | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags/PDF_avec_tags.pdf', 'detached': 'classpath:files/formats/PDF_avec_tags/signature_xades.xml'}                         | CAdES - Signature - PDF_avec_tags - signe_xades                        | 1      | 1      | without       | {}     |
            | HELIOS - XAdES env | Signature      | 'classpath:files/formats/PESALR1_unsigned.xml'                                                                                                                       | HELIOS - XAdES env - Signature - XML (UTF-8)                           | 1      | 1      | without       | {}     |
            | HELIOS - XAdES env | Signature      | 'classpath:files/formats/pesWithASAP_unsigned.xml'                                                                                                                   | HELIOS - XAdES env - Signature - XML (ISO-8859-1, PJ PDF incluses)     | 1      | 1      | without       | {}     |
            | PAdES              | Cachet serveur | 'classpath:files/formats/PDF_sans_tags/PDF_sans_tags.pdf',                                                                                                           | PAdES - Cachet serveur - PDF_sans_tags                                 | 1      | 1      | without       | {}     |
            | PAdES              | Cachet serveur | 'classpath:files/formats/PDF_sans_tags/PDF_sans_tags.pdf',                                                                                                           | PAdES - Cachet serveur - PDF_sans_tags - repositionnement signature    | 1      | 1      | without       | {}     |
            | PAdES              | Cachet serveur | 'classpath:files/formats/PDF_avec_tags/PDF_avec_tags.pdf',                                                                                                           | PAdES - Cachet serveur - PDF_avec_tags                                 | 1      | 1      | without       | {}     |
            | PAdES              | Cachet serveur | 'classpath:files/formats/PDF_avec_tags/PDF_avec_tags.pdf',                                                                                                           | PAdES - Cachet serveur - PDF_avec_tags - repositionnement signature    | 1      | 1      | without       | {}     |
            | PAdES              | Signature      | 'classpath:files/formats/PDF_sans_tags/PDF_sans_tags.pdf',                                                                                                           | PAdES - Signature - PDF_sans_tags                                      | 1      | 1      | without       | {}     |
            | PAdES              | Signature      | 'classpath:files/formats/PDF_sans_tags/PDF_sans_tags.pdf',                                                                                                           | PAdES - Signature - PDF_sans_tags - repositionnement signature         | 1      | 1      | without       | {}     |
            | PAdES              | Signature      | 'classpath:files/formats/PDF_avec_tags/PDF_avec_tags.pdf',                                                                                                           | PAdES - Signature - PDF_avec_tags                                      | 1      | 1      | without       | {}     |
            | PAdES              | Signature      | 'classpath:files/formats/PDF_avec_tags/PDF_avec_tags.pdf',                                                                                                           | PAdES - Signature - PDF_avec_tags - repositionnement signature         | 1      | 1      | without       | {}     |
            | XAdES det          | Signature      | 'classpath:files/formats/document_office/document_office.doc',                                                                                                       | XAdES det - Signature - DOC                                            | 1      | 1      | without       | {}     |
            | XAdES det          | Signature      | {'file': 'classpath:files/formats/document_office/document_office.doc', 'detached': 'classpath:files/formats/document_office/signature_cades.p7s'}                   | XAdES det - Signature - DOC - signe_cades                              | 1      | 1      | without       | {}     |
            | XAdES det          | Signature      | {'file': 'classpath:files/formats/document_office/document_office.doc', 'detached': 'classpath:files/formats/document_office/signature_xades.xml'}                   | XAdES det - Signature - DOC - signe_xades                              | 1      | 1      | without       | {}     |
            | XAdES det          | Signature      | 'classpath:files/formats/document_libre_office/document_libre_office.odt',                                                                                           | XAdES det - Signature - ODT                                            | 1      | 1      | without       | {}     |
            | XAdES det          | Signature      | {'file': 'classpath:files/formats/document_libre_office/document_libre_office.odt', 'detached': 'classpath:files/formats/document_libre_office/signature_cades.p7s'} | XAdES det - Signature - ODT - signe_cades                              | 1      | 1      | without       | {}     |
            | XAdES det          | Signature      | {'file': 'classpath:files/formats/document_libre_office/document_libre_office.odt', 'detached': 'classpath:files/formats/document_libre_office/signature_xades.xml'} | XAdES det - Signature - ODT - signe_xades                              | 1      | 1      | without       | {}     |
            | XAdES det          | Signature      | 'classpath:files/formats/PDF_sans_tags/PDF_sans_tags.pdf',                                                                                                           | XAdES det - Signature - PDF_sans_tags                                  | 1      | 1      | without       | {}     |
            | XAdES det          | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags/PDF_sans_tags.pdf', 'detached': 'classpath:files/formats/PDF_sans_tags/signature_cades.p7s'}                         | XAdES det - Signature - PDF_sans_tags - signe_cades                    | 1      | 1      | without       | {}     |
            | XAdES det          | Signature      | {'file': 'classpath:files/formats/PDF_sans_tags/PDF_sans_tags.pdf', 'detached': 'classpath:files/formats/PDF_sans_tags/signature_xades.xml'}                         | XAdES det - Signature - PDF_sans_tags - signe_xades                    | 1      | 1      | without       | {}     |
            | XAdES det          | Signature      | 'classpath:files/formats/PDF_avec_tags/PDF_avec_tags.pdf',                                                                                                           | XAdES det - Signature - PDF_avec_tags                                  | 1      | 1      | without       | {}     |
            | XAdES det          | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags/PDF_avec_tags.pdf', 'detached': 'classpath:files/formats/PDF_avec_tags/signature_cades.p7s'}                         | XAdES det - Signature - PDF_avec_tags - signe_cades                    | 1      | 1      | without       | {}     |
            | XAdES det          | Signature      | {'file': 'classpath:files/formats/PDF_avec_tags/PDF_avec_tags.pdf', 'detached': 'classpath:files/formats/PDF_avec_tags/signature_xades.xml'}                         | XAdES det - Signature - PDF_avec_tags - signe_xades                    | 1      | 1      | without       | {}     |
