global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'core'
    scrape_interval: 5s
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: [ 'core:8080' ]

  - job_name: 'crypto'
    scrape_interval: 5s
    metrics_path: '/crypto/actuator/prometheus'
    static_configs:
      - targets: [ 'crypto:8080' ]

  - job_name: 'local'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ '${PROMETHEUS_LOCAL_JOB_URL}:8080' ]
