global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'core'
    scrape_interval: 5s
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: [ 'core:8080' ]

  - job_name: 'crypto'
    scrape_interval: 5s
    metrics_path: '/crypto/actuator/prometheus'
    static_configs:
      - targets: [ 'crypto:8080' ]

  - job_name: 'pdf-stamp'
    scrape_interval: 5s
    metrics_path: '/pdf-stamp/actuator/prometheus'
    static_configs:
      - targets: [ 'pdf-stamp:8080' ]

  - job_name: 'local'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ "host.docker.internal:8080" ]
