global:
  scrape_interval: 15s
  evaluation_interval:

scrape_configs:
  - job_name: 'core'
    scrape_interval: 5s
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]

  - job_name: 'crypto'
    scrape_interval: 5s
    metrics_path: '/crypto/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8085' ]
